In [86]:
# Library yang digunakan
from nltk.tokenize import word_tokenize
import string
import pandas as pd
import numpy as np
import nltk
import emoji
import re
from sklearn.pipeline import Pipeline
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mirur\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

## 💡 Load Data

In [87]:
#Load Dataser
version = '5.3'
file_path = f"../data/review_genshin_{version}_cleaned.csv"
data = pd.read_csv(file_path)

In [88]:
# Show Dataset
data.head(10)

,ReviewID,Content,Score,ThumbsUpCount,at,AppVersion
0,869d8e47-1649-4823-a630-dd9dea341421,Good,5,0,2025-02-10 22:52:05,5.3
1,a885d7e9-e655-4583-9686-488fe34938ad,Moga menang rate off,5,0,2025-02-10 22:21:59,5.3
2,59910aae-3174-4ab6-8b9f-eb7d6ded0ffb,Udah ganti aja Jagan jadi game petualangan jad...,1,1,2025-02-10 22:05:06,5.3
3,5800da6b-abcb-48f6-8a63-6564c452d03b,"Menurutku sih bagus² aja game ini, game petual...",5,0,2025-02-10 20:54:30,5.3
4,63ca4e9b-0282-4e85-8f66-618a28c42628,Terlalu besar,4,0,2025-02-10 19:13:14,5.3
5,8cc8b53a-1be8-4071-8bf9-c9ca47bdfe7f,good,5,0,2025-02-10 18:47:56,5.3
6,c2c126c1-b22c-4cf5-854a-d3148abcd9c4,Saya benci game ini karna kalah rate off di ba...,1,2,2025-02-10 18:14:05,5.3
7,f37248a9-4043-4711-b143-e8ecb44204ce,jelek,1,1,2025-02-10 17:50:14,5.3
8,679cadaa-6195-4ed7-a4ec-3ecf2325a388,Game kikir,2,0,2025-02-10 17:40:43,5.3
9,5cde3567-3ff9-4660-8e29-dcf424b36dae,game kikir capek gw kalah rate off terus terus...,1,1,2025-02-10 17:36:10,5.3

In [89]:
data = data[data['Score'].between(1, 3)]

In [90]:
# proses case folding 
def casefolding(Content):
    Content = Content.lower()
    return Content
data['Content'] = data['Content'].apply(casefolding)
data.head()

,ReviewID,Content,Score,ThumbsUpCount,at,AppVersion
2,59910aae-3174-4ab6-8b9f-eb7d6ded0ffb,udah ganti aja jagan jadi game petualangan jad...,1,1,2025-02-10 22:05:06,5.3
6,c2c126c1-b22c-4cf5-854a-d3148abcd9c4,saya benci game ini karna kalah rate off di ba...,1,2,2025-02-10 18:14:05,5.3
7,f37248a9-4043-4711-b143-e8ecb44204ce,jelek,1,1,2025-02-10 17:50:14,5.3
8,679cadaa-6195-4ed7-a4ec-3ecf2325a388,game kikir,2,0,2025-02-10 17:40:43,5.3
9,5cde3567-3ff9-4660-8e29-dcf424b36dae,game kikir capek gw kalah rate off terus terus...,1,1,2025-02-10 17:36:10,5.3

In [91]:
def cleansing(Content):
    Content = emoji.replace_emoji(Content, replace='')  # Hapus semua emoji
    Content = Content.strip(" ")
    Content = re.sub(r'[?|$|.|!_:")(-+,]', '', Content)
    Content = re.sub(r'\d+', '', Content)
    Content = re.sub(r"\b[a-zA-Z]\b", "", Content)
    Content = re.sub(r'\s+', ' ', Content)
    return Content

data['Content'] = data['Content'].apply(cleansing)

In [92]:
# NLTK word tokenize


def word_tokenize_wrapper(text):
    return word_tokenize(text)


data['Content'] = data['Content'].apply(word_tokenize_wrapper)
data.head()

,ReviewID,Content,Score,ThumbsUpCount,at,AppVersion
2,59910aae-3174-4ab6-8b9f-eb7d6ded0ffb,"[udah, ganti, aja, jagan, jadi, game, petualan...",1,1,2025-02-10 22:05:06,5.3
6,c2c126c1-b22c-4cf5-854a-d3148abcd9c4,"[saya, benci, game, ini, karna, kalah, rate, o...",1,2,2025-02-10 18:14:05,5.3
7,f37248a9-4043-4711-b143-e8ecb44204ce,[jelek],1,1,2025-02-10 17:50:14,5.3
8,679cadaa-6195-4ed7-a4ec-3ecf2325a388,"[game, kikir]",2,0,2025-02-10 17:40:43,5.3
9,5cde3567-3ff9-4660-8e29-dcf424b36dae,"[game, kikir, capek, gw, kalah, rate, off, ter...",1,1,2025-02-10 17:36:10,5.3

In [93]:
normalizad_word = pd.read_csv("../data/normalisasi.csv")

normalizad_word_dict = {}

for index, row in normalizad_word.iterrows():
    if row[0] not in normalizad_word_dict:
        normalizad_word_dict[row[0]] = row[1] 

def normalized_term(document):
    return [normalizad_word_dict[term] if term in normalizad_word_dict else term for term in document]

data['Content'] = data['Content'].apply(normalized_term)

data.head()

C:\Users\mirur\AppData\Local\Temp\ipykernel_1792\2302089821.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if row[0] not in normalizad_word_dict:
C:\Users\mirur\AppData\Local\Temp\ipykernel_1792\2302089821.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  normalizad_word_dict[row[0]] = row[1]

,ReviewID,Content,Score,ThumbsUpCount,at,AppVersion
2,59910aae-3174-4ab6-8b9f-eb7d6ded0ffb,"[sudah, ganti, saja, jagan, jadi, game, petual...",1,1,2025-02-10 22:05:06,5.3
6,c2c126c1-b22c-4cf5-854a-d3148abcd9c4,"[saya, benci, game, ini, karena, kalah, rate, ...",1,2,2025-02-10 18:14:05,5.3
7,f37248a9-4043-4711-b143-e8ecb44204ce,[jelek],1,1,2025-02-10 17:50:14,5.3
8,679cadaa-6195-4ed7-a4ec-3ecf2325a388,"[game, kikir]",2,0,2025-02-10 17:40:43,5.3
9,5cde3567-3ff9-4660-8e29-dcf424b36dae,"[game, kikir, capek, saya, kalah, rate, off, t...",1,1,2025-02-10 17:36:10,5.3

In [94]:

from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
sw = pd.read_csv("../data/stopwords_id.csv")


def stopword_removal(Content):
    filtering = stopwords.words('indonesian', 'english')
    filtering.extend(sw)
    x = []
    data = []

    def myFunc(x):
        if x in filtering:
            return False
        else:
            return True
    fit = filter(myFunc, Content)
    for x in fit:
        data.append(x)
    return data


data['Content'] = data['Content'].apply(stopword_removal)
data.head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mirur\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,ReviewID,Content,Score,ThumbsUpCount,at,AppVersion
2,59910aae-3174-4ab6-8b9f-eb7d6ded0ffb,"[ganti, jagan, game, petualangan, game, cerita...",1,1,2025-02-10 22:05:06,5.3
6,c2c126c1-b22c-4cf5-854a-d3148abcd9c4,"[benci, game, kalah, rate, off, banner, weapon...",1,2,2025-02-10 18:14:05,5.3
7,f37248a9-4043-4711-b143-e8ecb44204ce,[jelek],1,1,2025-02-10 17:50:14,5.3
8,679cadaa-6195-4ed7-a4ec-3ecf2325a388,"[game, kikir]",2,0,2025-02-10 17:40:43,5.3
9,5cde3567-3ff9-4660-8e29-dcf424b36dae,"[game, kikir, capek, kalah, rate, off, terusan...",1,1,2025-02-10 17:36:10,5.3

### Proses Stemming dan Membuat file data baru (dataset yang sudah dibersihkan melalui proses NLTK)

In [95]:
# proses stemming
def stemming(Content):
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()
    do = []
    for w in Content:
        dt = stemmer.stem(w)
        do.append(dt)
    d_clean = []
    d_clean = " ".join(do)
    print(d_clean)
    return d_clean


data['Content'] = data['Content'].apply(stemming)

data.to_csv(f'../data/review_genshin_{version}_clear.csv', index=False)
data_clean = pd.read_csv(
    f'../data/review_genshin_{version}_clear.csv', encoding='latin1')
data_clean.head()

ganti jagan game tualang game cerita banyak bacot skip
benci game kalah rate off banner weapon karakter pacth
jelek
game kikir
game kikir capek kalah rate off terus kalah rate off hard pity
tombol skip story makan main cepat
kurang woy dialong sampah
server benerin bang jaring kenceng rossi main ghensin ngedrop
game
qol bad
tarik mb nya
dar saran fp tinggal game main biar nyesel download size gede gaban
cari material susah habis muncul badmood
please hoyoverse make it easy to find artifacts with substats and stats that always contain critical rate and critical damagelest the genshin game be considered the most miserly game ever because it always bothers its players in every way
butuh fitur skip cakap
voice les karakter dub english
bagus sih pelit banget sistem gacha dasar kikir
jelek
banyak yapping
tolong cut scene dialog gua main game nontonin cutscene abis nonton mending gua nonton film
have so much expectation for the natlan archon quest but comparing to what we got at fontaine and sumeru this is like downgrade the lore bomb are fewer and too much yapping that does not matter to the story
rate off nya kali gacha hoyoverse
kasih bintang game fitur skip story ngebosenin story nya panjang banget bicara tolong hoyo story banyak cerita ngantuk
tambah tombol skip dialogsatu dialog habis quest - menit aksi - menit bagus player bosan
bang tolong gen signature arlecchino dapet nyimittt
tombol skip
please add skip button story talk etc makes me sleepy playing this game gameplay  talk too much
lihat gameplay orang enak enak yaa pas antre jiabang bayikk
masuk minta
nya pgn aj gtu maintapi loading nya banget
gonlok data bet
cape beli item top up game gilir gacha susahdasar kikir impact
game explore fight ubah game bacot bacot
it  suck
story bagus bansos pelit banget primo susah dikumpulin dikit banget dapatin character nya sulit sial banget tembus pity untung menang rate of cerita rate ons kalah rate of pity atas kesal minimal rewardnya timpal dispend tuh ftc amerika tuntut lu sulit orang dapetin character ken
aneh login tulis minta coba
game dapet hard pity soft pity pity merah gereget banget hoki bingung hhhh gameplay nya tegang storynya bagus characternya imut imut lucu
game haram arte susahditinggal kondisi akun kait email akun ancam aman pdhl ngapa in loh pinjem in akun jg comeback lgsg bikin kecewa
tolong adakan fitur fokus story biar nyaman kelarin quest halang npc quest
kagak tombol skip yapping
alur cerita tarik layak ikut tambah banyak cakap buang inovasi tarik minat main sistem gacha mohon karakter artefak milik rate ampas alur cerita tarik ikut tolong story depan tolong evaluasi
fitur skip story suka game play kaya nyaman main
sistem gacha game buruk karakter artefak bagus buruk game gacha dialog digame skip dialog guna
keren
tambah fitur skip dialog
tambah fitur skip dialog
tolong trobosan bosan lama explorer bicara npc jawab ubah interaksi main konteks party orang dunia main genshin temu explore bareng batas orang sungguh bosan
ih jelek genshin voice eng nya ilang ilang kaya sag aftra amerika hilang ya cari voice actor ganti indonesia voice indonesia kaya gituan strike voice actor
tunggu update ulas
game gacha gajelas
banyak dialog skip dialog ngebuang buang
lumayan
fitur skip zaman baheula kagak yappingnya bosan kecewa beratt
game kikir
banyak yapping
game gacha wp dapet mulu
please tambahin reward story quest story quest habisin reward primo exp book
sistem banner gacha character susah drop characterminimal pity dapet char nya lh ngent
game jelek
malas kali kesini primogems kasih dikit banget uninstall
najis game bacot
game kikir gcha hard pity trozzz
yapping impact
genshin game bosok
mudah gacha nya donggg
soft pity kasih bintang
woi developer pas gacha pelit napa dapetin ya susah cok pantesan game kikir hadiah ya cuman dikit doang
tambah fitur skip dialog story tambah fitur reposisi tombol skill dll tambah fitur tombol pisah panjat dinding bangun masalah tarung pohon dinding tebing tambah fitur quickswap buka gameplay kompleks
ya genshin jembatan hitam login in game hitam bug plisss kasih benerin nya zian loh akun tiktok
banyak yepping skip ppk
main game kangen sih kangen kecewe outfit raiden shogun
akun ilang lu harap dari
the loading screen is so damn long it is very difficult to play ons smartphone if you accidentally exit the application you have to wait again for the damn long loading screen it  very hard to get star characters limited to fp players exploration rewards are little event period is too longplease shorten the chat during quest or provide skip feature so that players don  get bored while doing quest and one more thing why are there so little male characters
 uninstall this game because they don  fix the english voice over for long time they don  care anymore about the player
game nya kikir download loding nya download aset bikin
dialog gaada tombol skip menit ngomong haduh boring sumpah dapet primo spin engga pelit
game kikir artefak
mihoyo tambahin fitur skip dialog bosen banget liatin orang ngomong quest archon segi cerita seru world quest jujur bosenin banget tolong game skip dialog wuwadll
hoyoverse harap turun data aplikasi genshin impact hp ram hp cepat penuh panas
game buruk banget kesel dah download update data giga menuhin memori game jelek
tidak ada tombol skip questnya omong annoying
kasih bintang beneran game pelit banget
miyoho hormat tolong kasih hoki banner gacha muluk muluk banner karakter limited gakpp ken ngerain kek orang orang menang double pas gacha dua char biar skalian consnya aj player fp tuh gimna nabung primo butuh cok menang double gkpp lh menang pity tabung moga kritik saran dengar
sih akun gua banget gilir masuk login susah banget masuk pdhl akun sma pwnya bner game aneh akun suruh main ulang melulu
game guna gacha nya ampas mulu
bgst nggak hoki
tolong optimal grafik forma keluar sebab device panas tingkat medium atur fps nya
game tolol survey tombol skip habis dev dongo
download data sekalisampai
game bagus pity kaya oelr
game kikir kalah rate off kasih hard pity bansos dikit cicil mending game belah
servernya parah
gamenya kesini film drakor bosen cumo omong doang menu skip
game of talk so many dialogue
download mb abis gb ya
ngirim kode verifikasi telat
banget ngehancurin ekspektasi kikir
login genshin ya apk nya download tolong baik
few months ago played it then after entering the fontaine quest was sad why archon hydro was killed by the developer she  really beautiful you know so hope the developers bring her back or replace her with furina the next archon is equal beautiful sedih develop
paksa mulu dari game pdhl hp lag sinyal bagus
singkatpadat genshin kikir
tolong tambahin fitur main download data jangang download data nya
kikir
download nya banget
arte sampah mulu pas up pas gacha ampas game pay to win sat
skip dialog
maaf bintang keluh quest bgitu hadiah quest nya minimal hadiah nya tolong adakan fitur skip bincang story ngantuk nunggu bicara tolong adakan fitur skip dialog cerita nya
gamenya jelek storynya ampas gamplay absurp big for this game
susah nak main
stop ngasih dehya kasihh arlechino guaa
hoyo tolong perhati player cewe susah ya karakter cowo playable jujur suka banget story nya game player cowo suka harem kau keluar karakter cewe tebak game flop ampas banget
game hoyo ane mainin kalah rate-off mihoyo ane
ngotak dikit wei spin zaman zhongli liris sampe nggak dapet baner rate of anjir kecewa sekian baner nggak dapet dapet karakter standar uninstall
grafik map desain grafis karakter nya bagus game open world genshin baik sisi cerita sampai kaum skip story gila lore ngikutin story story genshin banyak yapping dialog nggak guna muter-muter kosong buang admin tolong kembali story genshin impact ons to the point
story telling kelas kakap optimalin tombol skip nya biar tunjuk skip
nonton scene main game
sistem pergachaan domain artefak tolong mudah susah cari stat substat artefak bagus main bosan putus asa susah cari resin
why in the game  little bad for the audio even though ve tried various ways to fix it but it didn  work hope muihoyo can improve my problems
sistem gacha nya ampasdan memori hp nya dikit coba coba main game
world building bagus musik nya bikin tenangmines banyak dialog plus fitur skipmenit dengerin oceh bergunauntuk fight eksplor cmn butuh bnyak mnt inti mah tambahin fitur skip
game ramah anggur story npc ngalahin story utama bosen
main genshin putus pensi krna explorasi sulit  ngebosanin gacha karakter spesifik mudah explorasi hadiah puzzle sesuai jam selesai puzzle hadiah cuman primo smbil liat tutorial youtube banyak yapping selesai quest makan jam kesal mc tidk kembang region mc kuat lemah game rpg
bad game
jelek kayak
gacha system is scam pull and only got one lanyan they spamming me with chevreuse and rosaria
please add more male characters  tired of female characters whose costumes are getting sexier
hard pity stroy turut bosan
main nya game ttp kikir lu mihoyo
momen najis lu dapet bansos cicil pas gacha dapet gold hard pity pas dapet gold dapetnya standarcape cape nguli eksplor map sampe  pas gacha dapetnya standarhadiah quest dikit dialog seabadkek ekspektasi indah game ilangdah serah lu dev cape maennya
sampah
unduh data game gb sekian nunggu selesai sengaja tutup aplikasi yak unduh data gamenya gb abis kuota
game elit build char sulit lv up talent weakly boss gacha sempat minggu farm arte gacha emang game gacha tpi ya napa kyak adeknya triple honkai mudah build char
ya sinyal bagus login tulis koneksi putus batas pdhl coba berkalimohon bantu
this game is good but why the char is always womenplease hoyo atleast give us character male
males
download data nya banget tunggu zaman engak selesai selesai mohon download data cepat
pay to win
tolong developer size game tolong kecilin gb
banget karakter suara ngerjain quest event lentern rite suara kecewa sih nunggu suara
ganyu echo susah
inget banget kali main banner kleesebulan rilis gametp inget ulas edit kali kali ngerasain kalah rate off sampe kali untun pity atas semuadrama nang pindah tangan game baikhallah jadi kikirnyaevent kaga reward kaga durasi nya
game bagus tpi berat main saran versi lite nya cloud cakap alur cerita misi skip main hilang cakap alur cerita misi mohon baik fitur skip
developer dongo sih quest npcnya obrol skip cuman ngobrol npc sampe menit lu main cuman dengar ngoceh doang hah minimal kasih fitur skip dialog anj ngobrol npc
sistem gachanya kikir tombol skip dialog
skipping buang battery hp dngearin cerita ujung kelar mission event or karakter bentuk cerita apa genshin turut buang buang jam kira kerja daily hari kasih event bnyk buang battery hp main games
woy mna cowok hitam otot woy
game pelit masak karakter aj dapet gg pelit
banyak yapping
bahasa inggris suara karakter hilang bug ngalamin jugatolong fix
game buruk
gamenya kikir admin
data  memori download data game nya
jelek
mah game visual novel
ku mb main gb
kikir gacha susah
dev nya kikir kaya dev belah gaada ubah nya ubah konten end game kaya belah jalan loh lambat
game buruk developer dengar suara playernya beda game belah mana developer nya dengar keluh player
tolong bug log-in nya benerin susah main kadang log-in kadang kagak mohon benerin mihoyo kasih bintang
dialognyaaaa
kikir anying kalah rate off mulu
gwe main kasih pity rendah game ampas
bosan main game sistem gacha nya ampas banget topup gacha signature arlechino kalah senjata langit hard pity hedeh pensi sih dapat tahun main game saran main mending cari me drama game
jenuh game hoyo akun kalah rate off ah yaudahlah emang henti buang buang waktudan uang hasil game semangat kurang main game yah main sistem gacha see you
stabil perangkat
segi gameplay story bagus banget cma sistem gacha nya ampas banget menang rate off cma menang itu high pity tolong hoyo sistem gacha nya kyk gin sih cma gacha karakter senjata gacha artefak sampah ampas banget desain karakter akhir kecewa reward event cma fp dengerin player mu
ayo dev kali dengerin player ngehina player cowo emang banyak karakter fanservice karakter cowo dikit eksplorasi gilir karakter cewe game belah daun ya ngaruhin game rasa banget beda era mondo liyue banting fanservice abrek guna be fr hoyo the bills cant be this high
game pelit gapernah hoki game tmen win rate off hard pity kalah  expkore main game tolong hoyo susah endgame sumber primo lgii tambahin sumber primonyaa capek kalah rate off sm banner senjata tolong pisah bannernya hsr
lag
gim kikir karakter laki laki kurang liat puja incel desain character aneh
game ngebug login
game kikirudah pity dapet rate ons
cerita skip ngebosenin
ringanin pliss gamenya berat hp dihp satu kompatibel
hardpitty mulu system gachanya sehat hapus system rate ons  off enga minimal kurang pitty tinggitambahkan reward primogem nya story banyak primogem nya chest enak cari primogem
bagus hd rendah nonn
masak ulang misi kali sebentar aj
game kikir fanservice karakter lelaki rangin story jelek relevant tawan banget nih target playernya
plis dub inggris ganti tambal pakai dubing jepang bahasa deflaut jpn males main story karakter bisu nutupin mata nyuruh nebak zhongli hutao
kurang dialog game eksplorasi banyak dialog sihh bikin males kasih tombol skip
main event daur ulang explore sulit tools hadiah cicil wkwk dah izin pensi ya
bug login benerin
tolong simpan nya turunin dikit ngapa gb kek kasihan hp kentang main
quest hadiah padan
gim aneh kikir buat sipit bikin merem
sistem gacha konyol game gacha signature scam lucu lucu
game kikir kasih bansos gameplay kaku story nggak nggak fitur skip story nggak sistem gacha jelek grafik
mihoyo primogem
event nya aneh rasio karakter nya jomplang banget gender
game pelit tolong baik
seru bosen map gede sepi
tolong optimal perfoma spesifikasi hp
can  skipp yapping can  show full wish history
woi nge bug cepet diperbaikin males banget banget banget
fitur skip story
kecewa game bug login develooper tolong bugnya baik main game kecewa bug game alami kasih rating bintang
game out of context mmorpg kaya main game story telling quest banyak dialog fight tolong ubah genshin game mmorpg gane story telling
too much yapping
game jelek banget download data banget verifikasi integritas kompilasi shader banget dasar game jelek
game kotoll anjggg gua capr capee ngulii dapet monaaa bnagsat
tumbuh genshin haha mei sampe
perfect
tolong updatenya cepat babi kasihan suka speed run login nggak ngapa ngapain
topup akun hilang pas update pindah mihoyo hoyovers kesel akun cuman bilang benci game teman teman orang henti main game lanjut cs anggap serius
suka game cerita saji tarik main game kualitas game turun akibat banyak dialog poin cerita alur cerita nya repetitif harap depan rang dialog alur cerita moga game dengar feedback main main layak game zenless zona zero erti main terima kasih
mending tambahin fitur skip dialog side quest yapping anjay
tambahin fitur pvp
apes mulu game allahhh pls kasih arle sign
game kikir sampe ubun ubun rate ni game mending sodaranya ngasih bansos kek hujan langsung jedarrr tinggal claim gaush nunggu main apala lamain gtu dkit
buriq
ko bae
game nya bagus kocak nonton drakor selesai crita
ukur hp gede pdhl gamenya bagus gpplah kapan download
knl hard pity temen temen hoki langsung pilkas tolong rerun benner klee plsss
loh out mulu hp login pakai email tetep aj bilang sesi habis sila login ulang
android pakai controllersudah tunggu
dialogkebanyakan bacot
tolong banget tambahin keyboard mouse gameplay versi mobile tambahin kasi bintang
gamenya ngebug ndk login make akun email tanggung hoyo
susah login
don  need your story just want to play it for fun and battle not hear the story of every boring conversation please make feature that player can skip the dialogue it  hell of boredome
rate gacha ampassss
guna pc make lossless scaling naik fpsapakah kena ban
malas tanggap
coba download bagus sihh sayang download data banget sumpah memo download data selesai ken banget mainin ya  tolong download data rang ken banget main
game elek
ngbrol kena leg ngulang sih
bantu pulih akun sayasetelah kali update tahun mainkq hilang yaa
tolong quest banyak cerita
akun gua kena bug mulu tolong baik
kikir impect
artefak jelek terus mood main
really boring archon quest waste my long weekend for this straightforward story my ahh it  just another power of friendship story with stakes and spices the natlan characters have nothing  going ons for them except patriotism heavy glazing for traveler too which takes too much screentime  gives nothing else story-wise except cringe what clownish take for what  supposed to be the nation of war at least the dinosaurs are cute as clunky to use as they are
tolong adil mc nya condong aether doang bagus nerima keluh kesah player
kikir cahr susah
tolong kurang data nya
atlest kasih fitur skip side quesst kek annoying banget enak explore tb tb ketrigger quest yaping nya banget
game yapping banyak story telling open word banyak tarung yapping game kikir pelit
unduh data
hope getting more reward and decrese chance getting character in hard pity
donlod loding nya bangett sampe jam kali kecewa banget si
donlout data nya
idk but boring story
download pas unduh data jam pagi sampek jam sore persen moga download cepat masuk
game kikir pelit banget player nya
game sampah quest nabrak nikmat gamenya
was defending this game when ur st anniv but for now this game is in its downfall
karakter laki dikit banget bosan liat cewek
- ku kasi bintang alas kenapaterlalu dialog banyak omong sistem gacha ampas ping edit kontrol layar
kecewa hutao gajadi mti
cerita nya bagus terkadang banyak basa basi bikin bosen
bad content
kikir minimal kasih male chara
susah login ulang suka logout akun ngebug ngebuka aplikasi
pas natlan alur nya ngebosenin
stat artefak parahtiap def hp masuk aneh mlu coba fix rate stat artefak biar bkin player rugi material tingkatin rate crit biar player puas terima kasih
game kikir
kasih bansos honkai star railll
dev malas kasih bintang
jelek banget tergeting incel too much karakter waifu backstory sembarang building muas incel archon quest natlan region hasil booming karakter laki laki bintang already spent too much in this game and this is how hoyoverse treat me
kurang inovasi konten saji ulang peristiwa unsur benar segar minim tantang event tarung saji tantang main main dekat fanservice fanservice kurang kualitas narasi karakter game
keren anomali imut kecewa
where are the male characters at
nyediain cs dipake ngasih data lengkap nya uidusernamelong devicebefore gmailtgl pembuatanfirst deviceinvoicebukti gameplay dll tolak mulu hadeh
game kikir
enough with the fan service and add more male characters
tele mc canon aether milih mc aether lumine cerita lambat minimal ceritain lore kek apa cerita maju fokus fan service loml
kwontollll gacha jembod
kikir karakter cowok kikir kikir impact tolong bansos buat playable character cowok main rilis kecewa berat game lama gooner bait beneran dawei mohon dengar keluh kesah player
game cakap gajelas sampah
after years nothing change with anniversary gift any other gacha games  genshin even after years
not aether only give lumine some arts bruh
kurang dialog panjang- panjangin inti ditunjukin yapping story char cowo dikit moga sneznahya san region char cowo playable rangin yapping nya
give lumine justice
game pelit
sedih hoyoverse anak tiri lumine mc wanita jujur bingung guna pilih mc lelaki perempuan sorot laki event highlightnya kasih ke-aether mc lumine protes dengar sungguh dev game toxic protes player china dengar betapa lucu
tinggal bentar suruh download data ulang
pilih mc lumine art event in game aether maksain si udel mandi chara cewek livestream kocak kocak oh transgender ya okiku one piece mandi cewek makan tu bawel player emang dasar company gaje
dawei banyakin cowok nya banyakin cewek melulu
tambah tombol skip dialog harga

,ReviewID,Content,Score,ThumbsUpCount,at,AppVersion
0,59910aae-3174-4ab6-8b9f-eb7d6ded0ffb,ganti jagan game tualang game cerita banyak ba...,1,1,2025-02-10 22:05:06,5.3
1,c2c126c1-b22c-4cf5-854a-d3148abcd9c4,benci game kalah rate off banner weapon karakt...,1,2,2025-02-10 18:14:05,5.3
2,f37248a9-4043-4711-b143-e8ecb44204ce,jelek,1,1,2025-02-10 17:50:14,5.3
3,679cadaa-6195-4ed7-a4ec-3ecf2325a388,game kikir,2,0,2025-02-10 17:40:43,5.3
4,5cde3567-3ff9-4660-8e29-dcf424b36dae,game kikir capek kalah rate off terus kalah ra...,1,1,2025-02-10 17:36:10,5.3