In [76]:
# Library yang digunakan
from nltk.tokenize import word_tokenize
import string
import pandas as pd
import numpy as np
import nltk
import emoji
import re
from sklearn.pipeline import Pipeline
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mirur\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

## 💡 Load Data

In [77]:
#Load Dataser
version = '5.5'
file_path = f"../data/review_genshin_{version}_cleaned.csv"
data = pd.read_csv(file_path)

In [78]:
# Show Dataset
data.head(10)

,ReviewID,Content,Score,ThumbsUpCount,at,AppVersion
0,2cf85c2d-bc47-4030-9eca-ac000d46d82f,HELLO GENSHIN IMPACT I HAVE A LITTLE COMPLAINT...,5,0,2025-04-10 18:30:38,5.5
1,c97ec484-677d-4d17-b330-39502dd9b045,"Saran buat dev dioptimalkan lagi game ya, 2020...",1,0,2025-04-09 20:08:42,5.5
2,4550d4ff-d199-4983-81f5-a299b923ab19,good,5,0,2025-04-09 19:57:42,5.5
3,4318f7e7-e90b-4fd8-acae-45a2dd6e7452,game nya asik bet anjay,5,0,2025-04-09 19:55:05,5.5
4,fa38b679-0c26-4922-82c5-08474ed35fed,Ini game atau seni yaallah soalnya bgus bgt!!!...,5,0,2025-04-09 19:46:49,5.5
5,0c916f46-3643-41fe-a684-fa4f9a2e3dad,good game,5,0,2025-04-09 19:32:24,5.5
6,65b278f4-fb78-477b-8368-dd5f310f6d27,oke saya tidak ada lagi yang ingin di sampaika...,5,211,2025-04-09 19:26:42,5.5
7,5708cf2e-fe86-4db2-bba1-2da54f464898,game ny oke tp g tau np itu skrg klo mau downl...,3,0,2025-04-09 19:10:07,5.5
8,ad36239f-9f4d-4cb7-a8cd-57a68a7e1466,perfect.,5,0,2025-04-09 19:03:40,5.5
9,70e0d324-08bb-4e23-9690-01540ce3f137,"Bagus sih, untung gak kikir seperti dulu wkwk",5,0,2025-04-09 18:59:10,5.5

In [79]:
data = data[data['Score'].between(1, 3)]

In [80]:
# proses case folding 
def casefolding(Content):
    Content = Content.lower()
    return Content
data['Content'] = data['Content'].apply(casefolding)
data.head()

,ReviewID,Content,Score,ThumbsUpCount,at,AppVersion
1,c97ec484-677d-4d17-b330-39502dd9b045,"saran buat dev dioptimalkan lagi game ya, 2020...",1,0,2025-04-09 20:08:42,5.5
7,5708cf2e-fe86-4db2-bba1-2da54f464898,game ny oke tp g tau np itu skrg klo mau downl...,3,0,2025-04-09 19:10:07,5.5
18,10d4af53-7931-46d0-b46e-918ad1034af7,skrng berasa jadi game bayi,1,0,2025-04-09 16:03:06,5.5
21,4ff06131-445f-42dc-97b9-6a5534edf433,"game ini makin lama makin ampas, jaringan, gac...",1,5,2025-04-09 15:01:27,5.5
26,b5995cea-8885-462c-af95-1e732b72744a,ukuran datanya gak ngotak sumpah download haru...,1,0,2025-04-09 12:53:25,5.5

In [81]:
def cleansing(Content):
    Content = emoji.replace_emoji(Content, replace='')  # Hapus semua emoji
    Content = Content.strip(" ")
    Content = re.sub(r'[?|$|.|!_:")(-+,]', '', Content)
    Content = re.sub(r'\d+', '', Content)
    Content = re.sub(r"\b[a-zA-Z]\b", "", Content)
    Content = re.sub('\s+', ' ', Content)
    return Content

data['Content'] = data['Content'].apply(cleansing)

<>:7: SyntaxWarning: invalid escape sequence '\s'
<>:7: SyntaxWarning: invalid escape sequence '\s'
C:\Users\mirur\AppData\Local\Temp\ipykernel_1792\3986272389.py:7: SyntaxWarning: invalid escape sequence '\s'
  Content = re.sub('\s+', ' ', Content)

In [82]:
# NLTK word tokenize


def word_tokenize_wrapper(text):
    return word_tokenize(text)


data['Content'] = data['Content'].apply(word_tokenize_wrapper)
data.head()

,ReviewID,Content,Score,ThumbsUpCount,at,AppVersion
1,c97ec484-677d-4d17-b330-39502dd9b045,"[saran, buat, dev, dioptimalkan, lagi, game, y...",1,0,2025-04-09 20:08:42,5.5
7,5708cf2e-fe86-4db2-bba1-2da54f464898,"[game, ny, oke, tp, tau, np, itu, skrg, klo, m...",3,0,2025-04-09 19:10:07,5.5
18,10d4af53-7931-46d0-b46e-918ad1034af7,"[skrng, berasa, jadi, game, bayi]",1,0,2025-04-09 16:03:06,5.5
21,4ff06131-445f-42dc-97b9-6a5534edf433,"[game, ini, makin, lama, makin, ampas, jaringa...",1,5,2025-04-09 15:01:27,5.5
26,b5995cea-8885-462c-af95-1e732b72744a,"[ukuran, datanya, gak, ngotak, sumpah, downloa...",1,0,2025-04-09 12:53:25,5.5

In [83]:
normalizad_word = pd.read_csv("../data/normalisasi.csv")

normalizad_word_dict = {}

for index, row in normalizad_word.iterrows():
    if row[0] not in normalizad_word_dict:
        normalizad_word_dict[row[0]] = row[1] 

def normalized_term(document):
    return [normalizad_word_dict[term] if term in normalizad_word_dict else term for term in document]

data['Content'] = data['Content'].apply(normalized_term)

data.head()

C:\Users\mirur\AppData\Local\Temp\ipykernel_1792\2302089821.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if row[0] not in normalizad_word_dict:
C:\Users\mirur\AppData\Local\Temp\ipykernel_1792\2302089821.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  normalizad_word_dict[row[0]] = row[1]

,ReviewID,Content,Score,ThumbsUpCount,at,AppVersion
1,c97ec484-677d-4d17-b330-39502dd9b045,"[saran, buat, dev, dioptimalkan, lagi, game, y...",1,0,2025-04-09 20:08:42,5.5
7,5708cf2e-fe86-4db2-bba1-2da54f464898,"[game, nya, oke, tetapi, tahu, np, itu, sekara...",3,0,2025-04-09 19:10:07,5.5
18,10d4af53-7931-46d0-b46e-918ad1034af7,"[sekarang, berasa, jadi, game, bayi]",1,0,2025-04-09 16:03:06,5.5
21,4ff06131-445f-42dc-97b9-6a5534edf433,"[game, ini, makin, lama, makin, ampas, jaringa...",1,5,2025-04-09 15:01:27,5.5
26,b5995cea-8885-462c-af95-1e732b72744a,"[ukuran, datanya, tidak, ngotak, sumpah, downl...",1,0,2025-04-09 12:53:25,5.5

In [84]:

from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
sw = pd.read_csv("../data/stopwords_id.csv")


def stopword_removal(Content):
    filtering = stopwords.words('indonesian', 'english')
    filtering.extend(sw)
    x = []
    data = []

    def myFunc(x):
        if x in filtering:
            return False
        else:
            return True
    fit = filter(myFunc, Content)
    for x in fit:
        data.append(x)
    return data


data['Content'] = data['Content'].apply(stopword_removal)
data.head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mirur\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,ReviewID,Content,Score,ThumbsUpCount,at,AppVersion
1,c97ec484-677d-4d17-b330-39502dd9b045,"[saran, dev, dioptimalkan, game, ya, edit, ula...",1,0,2025-04-09 20:08:42,5.5
7,5708cf2e-fe86-4db2-bba1-2da54f464898,"[game, nya, oke, np, download, data, aneh, ora...",3,0,2025-04-09 19:10:07,5.5
18,10d4af53-7931-46d0-b46e-918ad1034af7,"[berasa, game, bayi]",1,0,2025-04-09 16:03:06,5.5
21,4ff06131-445f-42dc-97b9-6a5534edf433,"[game, ampas, jaringan, gacha, karakter, artef...",1,5,2025-04-09 15:01:27,5.5
26,b5995cea-8885-462c-af95-1e732b72744a,"[ukuran, datanya, ngotak, sumpah, download, nu...",1,0,2025-04-09 12:53:25,5.5

### Proses Stemming dan Membuat file data baru (dataset yang sudah dibersihkan melalui proses NLTK)

In [85]:
# proses stemming
def stemming(Content):
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()
    do = []
    for w in Content:
        dt = stemmer.stem(w)
        do.append(dt)
    d_clean = []
    d_clean = " ".join(do)
    print(d_clean)
    return d_clean


data['Content'] = data['Content'].apply(stemming)

data.to_csv(f'../data/review_genshin_{version}_clear.csv', index=False)
data_clean = pd.read_csv(
    f'../data/review_genshin_{version}_clear.csv', encoding='latin1')
data_clean.head()

saran dev optimal game ya edit ulas pv buset dah story nya sangka game kasih bintang bagus lore storynya pingin ngikuti game edit maaf lorenya kek game bayi ya natlan negara perang kebun binatang kasih bintang kecewa benerrrrr
game nya oke np download data aneh orang selesai download data pas masuk game nya mlh selesai nya mah jdinya makan storage sm pulsa tolong dibenerin hoyo
asa game bayi
game ampas jaring gacha karakter artefak kit combat story ampas game ramah fp habis bosan pensi bosen
ukur data ngotak sumpah download nunggu jam jam hp panas bet
apa game fitur skip lagigame nya makan game nya pelit
woi hoyo
cakap skip buang reward tara kerja quest reward gacha player fp
game hoyoverse game sapi perah doang rate ampas
isi suara en hilang alas tanda tanda fix
optimal sinyal busuk banget mobile disconnect menit pdhl main game aman lancarr
seru
skip button just yapping game
samachar cowo nya dikit banget laut deh
game kikir main hp bagus ngelag explorenya rada gila mula suruh explore region cuman dapetin material upgrade char
bosen
add skip mode in story bro please boring game
apsih stuck sih tulis koneksi putus wifi anj masuk elemen layar putih smua gabisa masuk kocak
ping server asia benerin dah game dah ping nya ampas banget
kikir
bagus banget developer dengerin feedback playernya bahagia ketemu dev sikap kaya gin player kayak sukses ya
tolong minta dimatiin
game nya si enak otak
event alur cerita nya panjang mati film skalian jam parah banget bosan
pelit kli karakter dapet padahl ulang kli kasih la mudah minimal mohon dapet karakter ni nggk
hoyo char genshinnya buka ya pakaiannyakasian playernya kecilkalau naikin ratingnya naikin kek
hard pitybos susahga fitur bikin anak mohon kembang
game drama download data sampe nyesel gua download bangke
tolong mudah artefak random hadiah artefak tera masuk domain sesuai tera masuk domain original resin energi buang sia sia
game kikir
game ajar sabar syukur milik smuanya titip
game ramah player skip story kocak capek player mending main
game banyak yapping event yapping primo kalah rate off awas dapet radiance kau janji bikin tamat game snezhnaya dah capek main nya pensi penasaran dah terima kasih
bosenin mid story
game puki
agam elemen beda agam tim party elemen reaction kendala krusial alami banyak player mana resource perlu bangun stat karakter susah tambah durasi resin max artefak karakter susah dapat stat
overall bagus kadang quest karakter bisu english voice tolong quest langsung inti teks bosan
it  boring every time there  new female character you should also make male character too it  cool
rangin gb nya woiiii
kikir neng sm genshin kangen genshin yng
akun ilaaaaaamg
laen kali hoyovers ngasih bansos minimal gachanya hard bngsat beda bet ama belah bansos bnyk gacha pelit char limit smph
lelah dgn karakter famale update
game kikir
kikir baget dev nyagk dengerin player nya
berat game nya kikir adek adeknya tetep mainin
kikir
developer kikir
scam
got pain from co-op
berat hati kecewa layan cs scamer korban tipu akun
main game barbie tingkat kualitas minim qol story tarik gameplay keren monoton lambat devs kepala batu peduli komunitas player cn ayo game anime-style rpg kualitas rilis tinggal devs rakus
selesai update versi hp kompilasi shader mulu niat main suruh nunggu
trying this game to see how bad it actually is
farming artifact buruk kasih stats deff  guna resin sia sia
ramah
jelek
lumayankurangi yapping story
kasih bukti email maaf akun game pulih kasih bukti akun percaya betah main game akun kena hack melulu
battle monoton cerita mid dialog muter-muter bikin susah fokus cerita misi monoton bosenin banget dar eksplore ngalahin musuh puzzle
game jelek gabisa perfect dodge gbisa gsw
aneh developer nya
tolong ya dengerin saran player gameplaynya ngebosenin monoton gaada fitu skip dialog cepat kali player jam player duduk doang ngedengerin karakter ngoceh mending dialog eventnya nyambung lore eventnya cuman ya gitu-gitu gaada tarik sistem gacha ancur tpi dijelasin lebar didengerin ya
give us skip button
main kartu jam kasi jelek cuman misi doang susah bangetkalo ngasi misi yahh gin
asli game keren
sempet main loding nya kali bilang jalan
tombol skip
pity always deep
when chatting the story can not be skiped very boring please update skip the chat and provide dialogue only waste of time
main game versi kompatibel perangkat harap update genshin support android
semangat mihoyo
loading aki nungguin selesai
game nya ok tpi tolong musuh nya susah banget bikin mati karakter sih nyari artefak susah sih karakter kasih makan dikit kenyang cooldown makan nya banget tolong baik
game nya monoton begitu fan service main jijik karakter akan hilang true story nya cipta muas  gameplay natlan wow kecewa
jadiin capitano playable pls pdhl char nya ngaruh banget cerita kasi playable samsek playable char pengaruh sm cerita huft
main game untung mekanisme capturing radian muncul nya kalah rate off
ya lumayan kikir
suka patch natlan turut buruk astaga lihat karakter nya damn desain jelek jir nih game minim improve dev budeg gamau dengerin player sombong lu
game ampas
kumpul resin
bro game open world gin pakai controller
gamenya seru sizenya ngotak hp apa kayak main game gb dah eh update main developer update ngasih gb ngotak game belah berat
karakter laki laki kurang kecewa capitano playable dialog gamenya ulang dialog sinyal jelek dialog skip hsr
banget danwlot data
tunggu char male bugiel nya hoyo female char nya tu
kena rate off
mendownload data
moga konsep nya konsisten masuk natlan kemarin tepat pas hype nya palworld konsep iansan dl bocil sangar dah beda pas rilis sekian terima kasih
saran login offline download peta minta sumuanya penuh bintang
hate genshit rilis ubah qol lock balik paywall natlan immersion breaking karakter nya
ngelag woi ram gb berat maennya
anjing kga ngotak size data nya gb download
please help me fix the lag ons my phone so the game should be made easier to play ons phones with less power
kasih skip dialog hoyopek
kikir
tolong mudah dala eksplorasi
mohon mihoyo colldown resi cepat quest selesai ngapain malas explore
this game is absolute garbage the developers or even the whole company clearly don  care about their players they ve never listened and it  obvious they never will enjoy the money
game mantap
overall segi grafik nya bagus sesuai perangkat bosan quest milik cakap buang quest dunia tolong kurang dialog banyak aksi lawan monster artefak adil fp artefak ampas tolong besar stat sekian mksh
ngunduh nya game burik
bosan
game ringan
pity nya jelek player ftp
galat game prolog game galat pemakainan belah layar pengunaan aplikasi gotube putar lagu celah batu kali karakter diam jalan cuman galat atas game relog galat main mohon baik tangap
maksa fitur skip orang milik aktivitas liatin dialog npc orang sultan joki quest orang pindah game pensi
game kikir
game sapi perah mihoyo
developer coba ganti data gamedari gb gb
how many years left until you become generous let me guess around year
unduh data bett jam selesai
bocil genshin fomo nurunin rating
my account missing twice fp dark system mihoyo
kinich sign kinich raiden escoffier xilonen sign xilonen pokok menang rate off dilow pity
game kikir
player nya public enemy
just give us more male characters in this game
game ramah top up
hahaha akun ilang jir nge hubungin cs nya respon kacau kacau pikir akun tuh levil kecewa si minimal gabisa balikin akun ya respon si
banyak yeping ngantuk
maaf kasih bintang knpa pas main lag yah koneksi lancar ubah grafik parah device lag aneh tolong bantu susah kasih bintang
telat pakai banget fiturnya segi explore kasi player old
suara backsoundnya kaset rusak mobile
game kapitalis
game jelek mc kembang cmn sampah
tombol skip tambahin main quest orang dengerin yapping npc ber jam jam primo
developer buruk dengar feedback player parah qol nya tingkat gimmick sakit yapping gila muak main game primo dapat rekomen comeback main cari game
dapet varesa sm weapon nya high pity kasih
hilang bug limit login to many request akun ancam resiko
game pelit gacha hero bintang gua player fp jarang login ampass
mayan cuman pas main tidur seru quest archon si map nya gede sampe capek explore sumeru kalah rate off ueueue tidak apa apa kinich dah pulang overall lumayan ya cuman star main nge lag  apdet memo ku menang battle nya mayan ya cerita tarik ku tugas sekul suruh cerita fiksi hehehe sempet nang gara gara storynya ya mayan
putus ulang quet
design amburadul chara cowok woe
game banyak yapping bikin fitur skip
banyak yapping ngelarin story jam hadiah
-reward kikir -craft artifak sampah kikir -cooldown resin talu menit ngisi resin doang kikir -farming artifak sampah musuh spiral abyss bikin sulit balance - cooldown reset spiral abyss imaginarium kikir -event ras patch dekat region developer kikir
its getting worse
level source download nge-lag main map lag patah pc lancar genshin game pc
bosan sistem pity nang kalah rate off plus hard pity mulu kikir banget
masuk masuk
game layak main aspek kalah wuwa tombol skip mc sampah versi lemah mavuika material domain batas wuwa biaya resource butuh naik level karakter talent mahal banding wuwa material weekly boss random wuwa boss kali game kali
tolong akun hokiakun utama kalah rate off pity keatasrate ons pity atas semuatolong
game kaku npc interaktif muka nya template mc nya guna
mb gb nya dikecilin kek ukur mlbb hok biar main orang
banned orang alas main game hoyo akun email rabu april akun kebanned ngaruh akun hoyo honkaistarrail zenles zona zero main game akun kebanned hati hancur gabisa kecewa game hoyoverse beli hp spek bagus mainin game ban
main nunggu menit kocak
excuse me if you re reading this we need your help to put those english voice actors in their place right now the union vas harassing the non-union vas this put your game in bad situation because those union vas ruined your game image think about it your game looks bad because the staff makes it look bad aren  you going to do something about it don  think the hostility between us and cn really that matter matter if situation more critical like this happening right now
game kntllllllllyapping mlu ajinghhg side story jelekk jgtombol skipp ajggstory lu jelek bosenin pakai animasi template patah cringegk bikin bngsadd
game nya bagus cuman fitur cancel skill nya
improvisasi kembang game nya jelek bilang turun
mending hsr mah game kikir bansos dikit annvi kali pull gratis karakter standar mending hsr
tolong akun kena hack apa hiatus
game yapping tai hoyo pelit reward kikir burik
game tolol banyak yapping tolong tambah fitur skip story
game sampah banner character up tolol dapat satu banner up character dapat senjata up sekian item up artefak farming artefak kiamat gacha
genshin gmail verification delayed - minutes
gooner game
quest-quest banyak dialog super tolong ada tombol skip dialog karakter cowok kesini sekali lore-nya cerita biasa naruh bintang salah sesuai lore karakter tolong dibenerin design karakter sesuai kultur region dibenerin designnya region depan ya
plis rerun emilie banner
loading
game rpg mobile baik gua mainin nahh broitu ganti bintang developer sombong dengar feedback player
seru lag-nya dikit
tantang baru susah reward nya dikit aplah ni game main ngasih hadiah dikit banget tlol
developer kikir
asa game barbie char wanita desain ui bannernya feminim
stamina too little hard to activities --
gamenya bagus dev grafik anime real animasi bagus unik hero frame ratenya turun kadang lag beli hero masuk dunia dowload game lag memory sih
kikir apa
fitur skip nya mnaaa
buka hp buka
game kikir
bro want to plau genshin but xiaomi cant
loadingnya jaring bagus main kecewa duluan anjinggg
oii admin kasih nafa pelit bet dah aing dah habis primo njir nya
males banget game update patch download gb
game rakus uang
wuwa more better
game kikir
game gabut gakjelas
kasih artevak wangi
developer diskriminatif
mendonlot nya
game bodo data download gb
kompilasi shader
tombol skip
map natlan ngebug warna hitam
game bosan
main download gb
kbanyakan bicara alur cerita tolong bikin tombol skip scene kecuali scene utama inti main quest buat singkat cerita klik tombol skip scenenya game belah bikin kebnayakan player nyaman ketimbang dengarin scene ahrus pilih pilih ujung ngaruh quest dijalanin guna tolong developer bikin mudah
bug masuk gamenya
ehh kunyuk game pilih kasih cuman telat download shader doang gb dasar game kikir
hell kirain size nya -gb gb an
quest in natlan too much story it can take for admin watching their dialogue please add skip story button think not all of us enjoy the story some ppl jst want adventure not watching story if we want story we will go ons netflix and watch movie or anime
kikir bintang sih
waras ni game download suruh download gb anjir menang nih hp ku simpan gb
anj banget fitur telanjang
admin download ram
game kikir main ngasi bansos bagus
cutsene nya jelek animasi bibir suara nyambung grafik spesial bagus belah tuh honkai star rail niat banget bikin game sizenya gede gb cutsene nya jelek tampil karakter tamplete gamenya sulit elden ring bansos nya dikit banget
game kikir
coba fitur qol kasih paywall macem gamepad  fps exclusive iphone doank explorasi karakter limited
banyak nunggu
hp ku ngecrash ya ngecrash aman pas mo ganti server dari amerika asia tiba ngecrash gajelas
bagus sih gatau ngebag emng sinyal kaya ngerjain misi bicara npc kaya ngefrez diem ajh background gerak tungguin misi nya jdi mohon baik biar nyelesain quest nya
habis update gagal unduh data jaring error sila coba code- pakai wifi pakai data liat youtube mohon bantu hoyovers
jaring tolong dioptimalkanpadahal aplikasi aman main genshin impact ngelag parah
rate off kalah mulu pity trsg ksi menang cape cape farm ksi standard
data apl kecil rasa
game nya burik
update kemarin eh besok update maksud updatenya banget dikit update kompensasi cmn primo pelit banget emang game kikir
game yapping skip story minimal skip kasih ringkas story
bagus pw konten game jangkau
semenjak patch tepat banner karakter mavuika muncul event tarung spiral abyss buff nya karakter khusus andal nightsoul blessing gin ya genshin natlan muncul agustus taruh nightsoul blessing spiral abyss adil orang dapetin  milik karakter natlan saranin marketingmu ganti bug dibenerin
player keluh mendownload data update patch baru main update lagidan kalihal takut player nyaman main buang download data habis simpan mohon developer baik
bagus banget grafik bagus gameplaynya seru mantap
sinyal lancar suka ngelag pas main reset
cinta you banget genshin plis model ganti dikit kek nambahin people of color emang pakai culture orang minimal emang karakter representasi emang buat cina contoh game reverse milik karakter agam masuk player biarin ngumpulin debu implementasi
puzzle sulit tantang sulit
kasih tombol skip game banyak dialog quest sampe menit dialog kaya tol
game natlan jomplang banget nya gede ekspektasi region segi desain karakter buka little bit weird banding karakter cewek cowok nya astaga wkwkw heran iansan sepak terjal lol official fanart tolong cantum lumine pakai aether kasi mc cewek anak tiri
game nya seru sih main ya bug tolong solusi
the best deh gamenya unduh data yah saran tambah char cwo badan tegap muak liat femboy
update kali login game kompilasi shader makan males main nunggunyablama banget
ngapain jir jam cuman liat dialog doang mending game belah skip dialog
game is full of gooner people many people make bad things about this game make me piss me off pls don  make the character can ruin the fandom of this game
heywe need star male character
dowload data - jam tolong cepat dowload data nunggu
hp ramen
bnyak bnget pnyimpanan
fitur skip yapping sih
the problem is only in storage and centuries-long shader compilation
map bug kooooonnnn
gamenya bagus
kikir
male character dikit femalenya kinich da muncul male
update update fitur skip story
gin game bagus banget pelit hapus akun susah kek orang mati bugnya solusi kasih
apala ngmngnya update gb gb gin siudh mah nungguin implikasi shadernya banget lagicape nungguuu
saran sih mudah cari artefak bagus
genshin tawar cerita tarik region character sayang genshin muas player design character mekanisme kembang dengar masuk player moga depan ubah senang
woy hoyo karakter cowo cewe mulu bosan cewe cewe mulu sekali bikin karakter cowo jadiin karakter orang karakter cowo cewe lu
game hama
unduh tolong unduh lol
mantap dah support controller
dah download data nya jam main nunggu jam ken tinggalin ngulang nasib nasib
cari artifact bagus susah banget
ukur grafik kek kartun game cobak lawan monster karakter buriq buang memori simpan
suka genshin tolong minimal dengerin fans mihoyo adain fitur skip story males banget bikin boring banyak cerita masuk lore utama cerita nya bikin tarik banyak ngobrol gajelas buang buang bikin karakter cowo kek banyakin yakali cewe ngelesbi banyak fanservice desain karakter kesini jelek karakter splash art nya aj pantes komplain
device operasi device akses update versi
game lawak banyak yapping doang isi lawak su lu kagak yapping kasih jeda su ganti perang lawak ni game yapping su buang menit liat karakter npc yapping su su kikir hasil mana kagak comeback game lawak
kalah rate off njir
bosan
main langsung kasih karakter qiqi langsung uninstal
kikir
just talk to much bad game
in fitur skip story nya biar enak nunggu story an pencet pencet bosen main in ni geme awal enak pas main in bosen bet alur cerita nya banyak bacot doang
devnya nggak dengerin keluh player
bintang ok jelas sih genshin impact bagus update update itu nguras memori laginah updatenya berat tolong rangin ukur diplays tore tampil mb main full butuh gb memori hpku auto habis tolong rangin
why do you always release female characters to be where the boy or man
mang hoyo pelit primo
dev bapuk event nya kikirtidak fitur skip dialog
bintang support controller
update kali kali updatenya admin genshin impact sizenya gigaan update anjrit
artifact susah banget dapetinnyadapet artifact dah level rewardny jelek
banyak update
- format resign gim kikir sikma  sayee jaki sekibidi aura mewingrizzpunya mantanpernah naikin kuda kaki milik bmw  resign gim butut pelit asikkk asik bikin stres sepanjeng hari jeegim gabakal dimainin tidak ada bess had bess yogagim butut hok gim bikin wajeh saye pamarah
akun kena hack - kali ngisi form terima dah ngirim email hoyoverse dapet balesan otomatis
game kikir
banyak dialog ons point story quest minimal dengerin keluh kesah player player betah gamedev peduli ama player nya update nya monoton banyak nya jiplak rerun event
memori game nya
sih download lumayan dimainin pas main main loading masuk nya banget tolong diperbaikin
pra unduh data suruh update gajelas
si hoyovers updte mb jdi gb ngotak ngotak ajr game rusak updte rusak
nice trash roll artifact
gameplay monoton bosan tutup tarik developer dengar feedback main fitur skip story artefak loudout reward sesuai sistem gacha ramah fp konten endgame sistem resin leluasa tolong loh yaa developer jangn tuli bebal ubah tarik
emang unduh data gb boros banget
game nya butuh gb sehiga gabisa main gb tolong sedikit tin gb nya gb pakai banyak internet
sih kritik yaa hoyo sih quest hambar story nya bagus grafik nya mantap tolong yaa hoyo nya baik baik gara quest nya kompeten dialog nya ngerjain quest nya ngenikmati suasana game nya story hambarmales pingin pindah game ngerjain quest
senang mainin game dialog bosan genap main tiba update nge download data gb auto unistall
game kikirplis adain tombol skip alur story nya sesuai primo dapetin primo dikit alur tidak ada tombol skip
buff xiao
update naikin substat artefak scam kembang game bodoh
story bagus pancing story sumeru powercept nya kuat karakter ver meta desain karakter bagus detail tolong masak pity dapet chara limit reward quest event banget dapetin arte bagus susah sub stat miss
woilah game yaping nya kikir wes puwaket lengkap cik ku kasih varesa ku qiqi
plsss kasih fitur skip all pas dialog yapping nya banget anjir cm dikit ornag wibu coyy
game kikir

,ReviewID,Content,Score,ThumbsUpCount,at,AppVersion
0,c97ec484-677d-4d17-b330-39502dd9b045,saran dev optimal game ya edit ulas pv buset d...,1,0,2025-04-09 20:08:42,5.5
1,5708cf2e-fe86-4db2-bba1-2da54f464898,game nya oke np download data aneh orang seles...,3,0,2025-04-09 19:10:07,5.5
2,10d4af53-7931-46d0-b46e-918ad1034af7,asa game bayi,1,0,2025-04-09 16:03:06,5.5
3,4ff06131-445f-42dc-97b9-6a5534edf433,game ampas jaring gacha karakter artefak kit c...,1,5,2025-04-09 15:01:27,5.5
4,b5995cea-8885-462c-af95-1e732b72744a,ukur data ngotak sumpah download nunggu jam ja...,1,0,2025-04-09 12:53:25,5.5